#!/bin/bash

# This script opens a file in Neovim at a specific line and column number
# first input we ignore
_="$1"
input="$2"

# Get the file path, line number and column number from the input
FILE_PATH=$(echo "$input" | awk -F: '{ print $1 }')
LINE_NUMBER=$(echo "$input" | awk -F: '{ print $2 }')
COL_NUMBER=$(echo "$input" | awk -F: '{ print $3 }')

OPEN_COMMAND=":e $FILE_PATH | :$LINE_NUMBER"

TERMINAL="Kitty"
SESSION="sana"
WINDOW="client"
PANE=0

tmux has-session -t $SESSION 2>/dev/null

if [ $? != 0 ]; then
	echo "Session $SESSION does not exist."
	tmux new-session -d -s $SESSION -n $WINDOW -x "$(tput cols)" -y "$(tput lines)"
	tmux send-keys -t $PANE 'nvim' Enter
	tmux send-keys -t $PANE $OPEN_COMMAND Enter
	osascript -e 'tell application "'$TERMINAL'" to activate'
else
	tmux select-window -t $WINDOW
	tmux send-keys -t $PANE $OPEN_COMMAND Enter
	osascript -e 'tell application "'$TERMINAL'" to activate'
fi
