import = [
  '~/.config/alacritty/themes/themes/tokyo-night.toml'
]

[env]
TERM = "xterm-256color"

[window]
decorations = "Buttonless"
padding.x = 10
padding.y = 10
dynamic_padding = true
opacity = 0.9
blur = true

[font]
normal.family = "FiraCode Nerd Font Mono"
size = 18
offset.y = 14
glyph_offset.y = 4

[scrolling]
history = 10000

[colors]
cursor.text = "#000000"
cursor.cursor = "#ffffff"

[cursor]
style.shape = "Underline"

[mouse]
hide_when_typing = true
