#! /bin/bash

echo "\n"
echo "Installing..."
echo "\n\n\n"


# Link all files in /link to ~/<filename>
for f in .dotfiles/link/.*; do
	if test -f "$f"
	then
		echo "Creating link from $f to $(basename $f)"
		ln -s "$f" "$(basename $f)"
	fi
done


echo "\n\n\n"
echo "Installation complete."
echo "\n"
