#! /bin/bash

echo Running the installtion. Linking files.


# link the files
ln -s ~/.dotfiles/.bashrc 		~/.bashrc
ln -s ~/dotfiles/.vimrc 		~/.vimrc
ln -s ~/.dotfiles/.gitignore_global 	~/.gitignore_global
