#! /bin/bash


# Link all files in /link to ~/<filename>
for f in .dotfiles/link/.*; do
	if test -f "$f"
	then
		echo "Creating link from $f to $(basename $f)"
		ln -fs "$f" "$(basename $f)"
	fi
done


# Fix for .bash_profile and .bashrc
ln -fs ~/.bash_profile ~/.bashrc


echo "Dotfiles installed successfully!"
