source ~/.dotfiles/helpers/variables
source ~/.dotfiles/helpers/paths
source ~/.dotfiles/helpers/aliases

if [[ $OSTYPE == darwin* ]]; then
    source ~/.dotfiles/osx/osxrc
else
    source ~/.dotfiles/linux/linuxrc
fi

# Prevent Ctrl-S
stty -ixon
