filetype off

call plug#begin('~/.vim/plugged')
Plug 'airblade/vim-gitgutter'
Plug 'kien/ctrlp.vim'
Plug 'mileszs/ack.vim'
Plug 'nightsense/cosmic_latte'
Plug 'scrooloose/nerdtree'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
call plug#end()

filetype plugin indent on

" Colors
syntax enable
set background=dark
colorscheme cosmic_latte

" Leader commands
let mapleader = " "
nnoremap <Leader>ss :split<cr>
nnoremap <Leader>sv :vsplit<cr>
nnoremap <Leader>, :tabfind $MYVIMRC<cr>
nnoremap <Leader>f :NERDTreeToggle<cr>
nnoremap <Leader>l :noh<cr>:<backspace>

" Move between splits with ctrl+{h,j,k,l}
nnoremap <c-h> <c-w>h
nnoremap <c-j> <c-w>j
nnoremap <c-k> <c-w>k
nnoremap <c-l> <c-w>l

" Remaps for the lazy
nnoremap ; :
nnoremap :q :close

" Ctrl+P
let g:ctrlp_show_hidden = 1
let g:ctrlp_custom_ignore = {
  \ 'dir':  '\v[\/](node_modules|.git)$',
  \ 'file': '\v\.(exe|so|dll)$',
  \ 'link': '',
  \ }

" NERDTree
let g:NERDTreeIgnore = ['\.aux$', '\~$']
let g:NERDTreeWinSize = 50
let NERDTreeShowHidden = 1
let g:NERDTreeNodeDelimiter = "\u00a0"

" Airline
let g:airline_powerline_fonts = 1

" File associations
autocmd BufNewFile,BufRead *.hbs setlocal ft=html


set cursorline
set expandtab
set foldmethod=indent
set foldlevelstart=20
set hlsearch
set ignorecase
set mouse=a
set number
set shiftwidth=2
set softtabstop=2
set splitbelow
set splitright
set noswapfile
set nowrap
