#! /usr/bin/env NODE_PATH="/Users/anton/.dotfiles/scripts/node_modules" node -r esm -r globals

log(chalk.green("\n+++ GOOD MORNING! 👋  +++"));

log(`
- What was on your mind this morning?
- What should have been done yesterday?
- What is todays schedule?

- Answer any slack notifications
- Check GitHub notifications [https://www.github.com/notifications]
- Sweep email inbox [https://mail.google.com]

- Process the Todoist inbox
`);
