#! /usr/bin/env node

const chalk = require('chalk')

console.log(chalk.green('\n+++ GOOD MORNING! 👋  +++'));
console.log(`
- What was on your mind this morning?
- What should have been done yesterday?
- What is todays schedule?

- Answer any slack notifications
- Check GitHub notifications [https://www.github.com/notifications]
- Sweep email inbox [https://mail.google.com]

- Process the Todoist inbox
`);
