gui:
  statusPanelView: "allBranchesLog"
git:
  paging:
    pager: 'delta --dark --paging=never --hyperlinks --hunk-header-style="omit"'
theme:
  nerdFontsVersion: "3"

customCommands:
  - key: "<c-u>"
    command: "gh pr create --fill-verbose --web"
    context: "global"
    loadingText: "Creating PR..."
