gui:
  statusPanelView: "allBranchesLog"
  theme:
    nerdFontsVersion: "3"

git:
  paging:
    pager: 'delta --dark --paging=never --hyperlinks --hunk-header-style="omit"'

customCommands:
  - key: "<c-u>"
    command: "gh pr create --fill-verbose --web"
    context: "global"
    loadingText: "Creating PR..."
